# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f97049498d5c9a4b0e9fde4928b27cfdb8bf4acc6272f01057f56a978fc12d4e656adaca9e68346f1ade69fba6e3d0397173fa3cad8df1c4c5156f6f4664756

test:
  secret_key_base: 2d8448a3584e46e69834713dc795a3ea0bf3648fdffae1057d6f722cd42bf2392c8cf09704c4806e23fb9b0fa6e68aaf4a3afc294ae851e5113ff486b5ddde14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
